Repository GuiaBolso/pink-lemonade-web, pull requests merged in 2020-07, with the labels that each got.

#3 Feat: Tooltip
  libs/ui/src/index.ts
  libs/ui/src/lib/display/Tooltip/Tooltip.stories.tsx
  libs/ui/src/lib/display/Tooltip/Tooltip.style.tsx
  libs/ui/src/lib/display/Tooltip/Tooltip.tsx
  libs/ui/src/lib/display/Tooltip/index.ts
Labels: enhancement

#4 Feat/modal
  libs/ui/.eslintrc
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/ui/src/index.ts
  libs/ui/src/lib/forms/index.ts
  libs/ui/src/lib/notification/Modal/Alert.stories.mdx
  libs/ui/src/lib/notification/Modal/Blank.stories.mdx
  libs/ui/src/lib/notification/Modal/Dialog.stories.mdx
  libs/ui/src/lib/notification/Modal/Modal.container.tsx
  libs/ui/src/lib/notification/Modal/Modal.context.tsx
  libs/ui/src/lib/notification/Modal/Modal.stories.mdx
  libs/ui/src/lib/notification/Modal/Modal.style.ts
  libs/ui/src/lib/notification/Modal/Modal.tsx
  libs/ui/src/lib/notification/Modal/ModalProps.ts
  libs/ui/src/lib/notification/Modal/index.ts
  libs/utils/CHANGELOG.md
  libs/utils/package.json
  libs/utils/src/index.ts
  libs/utils/src/lib/scales/hex-to-rgb/hex-to-rgb.spec.ts
  libs/utils/src/lib/scales/hex-to-rgb/hex-to-rgb.ts
  package-lock.json
  package.json
Labels: documentation, enhancement

#17 fix: 🐛 cancel subscribe
  libs/ui/src/lib/notification/Modal/Modal.tsx
Labels: bug

#21 style: 💄 melhorias no eslint
  .eslintrc
  .vscode/extensions.json
  .vscode/settings.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/ui/src/lib/notification/Toast/Toast.tsx
  libs/utils/CHANGELOG.md
  libs/utils/package.json
Labels: enhancement

#24 Feat/progress bar
  libs/ui/.storybook/main.js
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/ui/src/assets/images/icons/check.svg
  libs/ui/src/index.ts
  libs/ui/src/lib/notification/ProgressBar/ProgressBar.stories.tsx
  libs/ui/src/lib/notification/ProgressBar/ProgressBar.style.ts
  libs/ui/src/lib/notification/ProgressBar/ProgressBar.tsx
  libs/ui/src/lib/notification/ProgressBar/index.ts
  libs/ui/src/lib/notification/index.ts
  package-lock.json
  package.json
Labels: enhancement

#26 feat: 🎸 add CardHeader
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/ui/src/designSystem/tokens/guiaBolso.ts
  libs/ui/src/lib/containers/CardHeader/CarHeader.style.ts
  libs/ui/src/lib/containers/CardHeader/CardHeader.spec.tsx
  libs/ui/src/lib/containers/CardHeader/CardHeader.stories.tsx
  libs/ui/src/lib/containers/CardHeader/CardHeader.tsx
  libs/ui/src/lib/containers/CardHeader/__snapshots__/CardHeader.spec.tsx.snap
  libs/ui/src/lib/containers/CardHeader/index.ts
  package-lock.json
  package.json
Labels: enhancement

#27 chore: 🤖 add chromatic to public storybook
  .github/workflows/master.yml
  build-storybook.log
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/ui/src/lib/notification/Modal/Alert.stories.mdx
  package-lock.json
  package.json
  workspace.json
Labels: enhancement

#28 chore: 🤖 add flag to exit on publish storybook
  .github/workflows/master.yml
  package.json
Labels: enhancement

#30 Refactor/card component
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/ui/src/index.ts
  libs/ui/src/lib/containers/Card/Card.stories.tsx
  libs/ui/src/lib/containers/Card/Card.style.ts
  libs/ui/src/lib/containers/Card/Card.tsx
  libs/ui/src/lib/containers/Card/CardContent/CardContent.stories.tsx
  libs/ui/src/lib/containers/Card/CardContent/CardContent.style.ts
  libs/ui/src/lib/containers/Card/CardContent/CardContent.tsx
  libs/ui/src/lib/containers/Card/CardFooter/CardFooter.stories.tsx
  libs/ui/src/lib/containers/Card/CardFooter/CardFooter.style.ts
  libs/ui/src/lib/containers/Card/CardFooter/CardFooter.tsx
  libs/ui/src/lib/containers/Card/CardHeader/CardHeader.spec.tsx
  libs/ui/src/lib/containers/Card/CardHeader/CardHeader.stories.tsx
  libs/ui/src/lib/containers/Card/CardHeader/CardHeader.style.ts
  libs/ui/src/lib/containers/Card/CardHeader/CardHeader.tsx
  libs/ui/src/lib/containers/Card/CardHeader/__snapshots__/CardHeader.spec.tsx.snap
  libs/ui/src/lib/containers/Card/index.ts
  libs/ui/src/lib/containers/CardHeader/index.ts
  libs/ui/src/lib/display/Text/Text.style.ts
  libs/ui/src/lib/forms/Action/Action.stories.tsx
  libs/ui/src/lib/forms/Action/Action.style.tsx
  libs/ui/src/lib/forms/Action/Action.tsx
  libs/ui/src/lib/forms/Action/ArrowLeft.icon.tsx
  libs/ui/src/lib/forms/Action/ArrowRight.icon.tsx
  libs/ui/src/lib/forms/Action/index.ts
  libs/ui/src/lib/forms/Button/Button.tsx
Labels: enhancement
